{% set name = "pydppl" %}
{% set version = "0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    path: ..

build:
    number: 0
    skip: True  # [not linux]
    script_env:
        - ONEAPI_ROOT

requirements:
    build:
        - {{ compiler('cxx') }}
    host:
        - setuptools
        - cffi >=1.0.0
        - cython
        - cmake
        - python
        - make
        - numpy >=1.17
    run:
        - python
        - numpy >=1.17
        - cffi >=1.0.0

about:
    home: https://github.com/IntelPython/PyDPPL.git
    summary: 'A lightweight Python wrapper for a subset of OpenCL and SYCL API.'

extra:
    recipe-maintainers:
        - diptorup deb
