{% set name = "dppy" %}
{% set version = "v0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    path: ..

build:
    number: 0
    skip: True  # [not linux]

requirements:
    build:
        - {{ compiler('cxx') }}
    host:
        - cffi >=1.0.0
        - cmake
        - python
        - make
        - ocl-icd
        - numpy >=1.17
        - libusm
    run:
        - python
        - numpy >=1.17
        - cffi >=1.0.0
        - ocl-icd
        - ocl-icd-system
        - libusm

about:
    home: https://github.intel.com/SAT/dppy.git
    summary: 'A lightweight Python wrapper for a subset of OpenCL and SYCL API.'

extra:
  recipe-maintainers:
        - diptorup deb
